***
---
# **Table of Contents**
> importing `pandas`

> ## __Series__
> * Introduction to `Series`
> * Creating `Series`
>
> ## __Common Series Creation Customizations__
> 1. `index` Parameter
> 2. `dtype` Parameter
> 3. `name` Parameter

> ## __DataFrame__
> * Introduction to `DataFrme`
> * Creating `DataFrame`
>
> ## __Common DataFrame Creation Customizations__
> 1. `index` Parameter
> 2. `columns` Parameter
---
***

### imporing pandas
To use `pandas`, import it using the statement `import pandas as pd`. The `as pd` is a universally accepted community convention that allows you to make the library's name shorter and easier to use. Pandas is typically imported at the very top of notebooks in the first executable cell.

In [1]:
import pandas as pd

## **Series**
---

### What Series is
A Pandas Series is a one-dimensional labeled array capable of holding any data type, such as integers, floats, strings, or Python objects. Conceptually, it is like a single column in an Excel spreadsheet or a database table.

### Creating Series
To create a Pandas Series, use the `pd.Series()` constructor. Series can be build from various data sources like Python lists, NumPy arrays, dictionaries, or scalar values.

In [2]:
# 1. Creating an empty Series
my_series = pd.Series()
my_series

Series([], dtype: object)

In [3]:
# 2. From a Python List or Tuple
data_list = ["Apple", "Banana", "Oringe"]
my_series = pd.Series(data_list)
my_series

0     Apple
1    Banana
2    Oringe
dtype: object

In [4]:
# 3. From a Dictionary (Keys become the index labels)
my_series = pd.Series(data={"a": 200, "b": 400, "c": 500})
my_series

a    200
b    400
c    500
dtype: int64

In [5]:
# 4. From a Scalar (Repeats value across the given index)
my_series = pd.Series(10, index=[x for x in "abcd"])
my_series

a    10
b    10
c    10
d    10
dtype: int64

In [6]:
# 5. From a Python fuction (range)
my_series = pd.Series(range(50, 75, 5))
my_series

0    50
1    55
2    60
3    65
4    70
dtype: int64

In [7]:
# 6. From a Numpy Array
import numpy as np
np_data = np.array([1.4, 3.4, 8])
my_series = pd.Series(np_data)
my_series

0    1.4
1    3.4
2    8.0
dtype: float64

In [8]:
# 7. From a DataFrame
data = {
    "Name": ["Ali", "Mohammad", "Sadiq"],
    "Age": [22, 30, 15]
} 
user_data = pd.DataFrame(data)
user_names = pd.Series(user_data["Name"])
user_names

0         Ali
1    Mohammad
2       Sadiq
Name: Name, dtype: object

#### Image:
![Image of a CSV File](../data/images/csv-file.png)

In [9]:
# 8. Creating a Series from a CSV file
make_series = pd.read_csv("../data/csv-files/car-sales.csv", usecols=["Make"]).squeeze("columns") # Selects Make column from car-sales.csv
make_series

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

#### Image:
![Image of an Excel File](../data/images/excel-file.png)

In [10]:
# 9. Creating a Series from a Excel file
price_series = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols=["Price"]).squeeze("columns") # Selects Price column of car-sales.xlsx
price_series

0     $4,000.00
1     $5,000.00
2     $7,000.00
3    $22,000.00
4     $3,500.00
5     $4,500.00
6     $7,500.00
7     $7,000.00
8     $6,250.00
9     $9,700.00
Name: Price, dtype: object

#### Image:
![Image of a Json File](../data/images/json-file.png)

In [11]:
# 10. Creating a Series from a Jon File
json_data = pd.read_json("../data/json-files/house-price-parquet.json", lines=True)
stories_series = json_data["stories"] # Selects stories column of house-price-parquet.json
stories_series.head()

0    3
1    4
2    2
3    2
4    2
Name: stories, dtype: int64

## __Common Series Creation Customizations__
---

### 1. `index` Parameter
The `index` parameter specifies the axis labels used to identify each element within the one-dimensional array. 

By default, if no index is passed, pandas automatically assigns a sequential integer index starting from `0`.

In [12]:
# 1.1 Default Index
my_series = pd.Series([4, 9, 8, 4, 2])
my_series

0    4
1    9
2    8
3    4
4    2
dtype: int64

In [13]:
# 1.2 Custom Indexs Using a Python List, Tuple or Numpy Array
index_list = ["A", "B", "C", "D", "F"]
my_series = pd.Series([4, 9, 8, 4, 2], index=index_list)
my_series

A    4
B    9
C    8
D    4
F    2
dtype: int64

In [14]:
# 1.3 Custom Indexs Using range() Function
my_series = pd.Series([4, 9, 8, 4, 2], index=range(10, 20, 2))
my_series

10    4
12    9
14    8
16    4
18    2
dtype: int64

In [15]:
# 1.4 Giving Index with Data
dataset = {
    "Name": "Ahmad",
    "Age": 25,
    "Country": "Afghanistan"
}
my_series = pd.Series(dataset)
my_series

Name             Ahmad
Age                 25
Country    Afghanistan
dtype: object

### 2. `dtype` Parameter
The `dtype` parameter explicitly sets the data type of the underlying array. If you do not specify this parameter, Pandas will automatically infer the data type based on the values provided in your dataset.

In [16]:
# 2.1 Setting a Data Type
my_series = pd.Series(["1", "8", "9"], dtype=int)
my_series.dtypes

dtype('int64')

In [17]:
# 2.2 Optimizing Memory Usage
my_series = pd.Series(["22", "83", "11"], dtype="int16")
my_series.dtype

dtype('int16')

### 3. `name` Parameter
The `name` parameter allows you to assign a human-readable label or identifier to the `Series` object. It serves as a core piece of metadata that dictates how the `Series` interacts with other parts of the pandas library.

Why use the name parameter?
* __DataFrame Conversion:__ When converting a `Series` into a `DataFrame`, the name automatically becomes the column header.
* __Automatic Extraction:__ If you pull a single column out of a `DataFrame`, pandas automatically populates the name attribute of that resulting `Series` with the original column name.
* __Plotting & Display:__ The name is automatically utilized as a default axis or legend label when using the `Series.plot()` method. It also prints cleanly at the bottom of the `Series` terminal output.

In [18]:
# 3.1 Defining a name
dataset = {
    "Name": "Ahmad",
    "Age": 25,
    "Country": "Afghanistan"
}
info = pd.Series(dataset, name="User Info")
info

Name             Ahmad
Age                 25
Country    Afghanistan
Name: User Info, dtype: object

In [19]:
# 3.2 Converting to a DataFrame
dataset = {
    "Name": "Ahmad",
    "Age": 25,
    "Country": "Afghanistan"
}
info = pd.Series(dataset, name="User Info")
user_data = pd.DataFrame(info)
user_data

           User Info
Name           Ahmad
Age               25
Country  Afghanistan

In [20]:
# 3.3 Extracting Series from a DataFrame
data = {
    "Name": ["Ali", "Mohammad", "Sadiq"],
    "Age": [22, 30, 15]
} 
user_data = pd.DataFrame(data)
user_names = pd.Series(user_data["Name"])
user_names

0         Ali
1    Mohammad
2       Sadiq
Name: Name, dtype: object

## **DataFrame**
---

### What DataFrame is
A Pandas DataFrame is a two-dimensional, tabular data structure in Python that organizes data into rows and columns, much like an Excel spreadsheet or a SQL database table. It can store different types of data such as numbers, text and dates across its columns.

### Creating DataFrame
To create a pandas DataFrame, use the `pd.DataFrame()` constructor. Pandas allows us to create a DataFrame from many data sources. We can create DataFrames directly from Python objects like lists and dictionaries or by reading data from external files like CSV, Excel or SQL databases.

In [21]:
# 1. Creating an empty DataFrame
my_dataframe = pd.DataFrame()
print(my_dataframe)

Empty DataFrame
Columns: []
Index: []

In [22]:
# 2. From Python Lists or Tuple
names = ["Ali", "Mohammad", "Sadiq", "Hassan"]
ages = [22, 25, 18, 10]
users_info = pd.DataFrame(data={"Name": names,"Age": ages})
users_info

       Name  Age
0       Ali   22
1  Mohammad   25
2     Sadiq   18
3    Hassan   10

In [23]:
# 3. From a Python Dictionary
dataset = {
    "Name":["Ali", "Mohammad", "Hassan"],
    "Age": [22, 18, 25],
    "City": ["Kabul", "Bamyan", "Herat"]
}
users_info = pd.DataFrame(data=dataset)
users_info

       Name  Age    City
0       Ali   22   Kabul
1  Mohammad   18  Bamyan
2    Hassan   25   Herat

In [24]:
# 4. From a Numpy Array
data = {
    "A": np.array([1, 2, 3]),
    "B": np.array([4, 5, 6]),
    "C": np.array([7, 8, 9])
}
np_dataframe = pd.DataFrame(data)
np_dataframe

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

#### Image:
![Image of a CSV File](../data/images/csv-file.png)

In [25]:
# 5. From a CSV File
car_sales = pd.read_csv("../data/csv-files/car-sales.csv")
car_sales.head()

     Make  Color  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

#### Image:
![Image of an Excel File](../data/images/excel-file.png)

In [26]:
# 6. From an Excel File
car_sales_dataframe = pd.read_excel("../data/excel-files/car-sales.xlsx")
car_sales_dataframe.head()

     Make  Color  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

#### Image:
![Image of a Json File](../data/images/json-file.png)

In [27]:
# 7. From a Json File
house_price_parquet = pd.read_json("../data/json-files/house-price-parquet.json", lines=True)
house_price_parquet.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

## __Common DataFrame Creation Customizations__
---

### 1. `index` Parameter
The `index` parameter specifies the row labels for the resulting DataFrame object. If you do not explicitly pass this parameter, pandas automatically generates a default numeric sequence starting from `0` using `pandas.RangeIndex`.

In [28]:
# 2.1 Default Index
my_dataframe = pd.DataFrame({"A": [98, 34, 67, 8], "B": [22, 54, 82, 19], "C": [12, 90, 32, 43]})
my_dataframe

    A   B   C
0  98  22  12
1  34  54  90
2  67  82  32
3   8  19  43

In [29]:
# 2.2 Custom Indexs Using List
data = {
    "A": [98, 34, 67, 8],
    "B": [22, 54, 82, 19],
    "C": [12, 90, 32, 43]
}
indexs = ["CA", "NY", "AZ", "TX"]
my_dataframe = pd.DataFrame(data, index=indexs)
my_dataframe

     A   B   C
CA  98  22  12
NY  34  54  90
AZ  67  82  32
TX   8  19  43

In [30]:
# 2.3 Custom Index Using range() Function
data = {
    "A": [98, 34, 67, 8],
    "B": [22, 54, 82, 19],
    "C": [12, 90, 32, 43]
}
my_dataframe = pd.DataFrame(data, index=range(10, 14))
my_dataframe

     A   B   C
10  98  22  12
11  34  54  90
12  67  82  32
13   8  19  43

### 2. `columns` Parameter
The `columns` parameter explicitly sets or filters the column labels/names of your data table when initializing a new DataFrame.

In [31]:
# 1. Data with the Column Labels
data = {
    "Name": ["Ali", "Hassan", "Mohammad"],
    "Age": [24, 18, 22],
    "City": ["Kabul", "Bamyan", "Herat"]
}
std_info = pd.DataFrame(data)
std_info

       Name  Age    City
0       Ali   24   Kabul
1    Hassan   18  Bamyan
2  Mohammad   22   Herat

In [32]:
# 2. Specifying Column Order
data = {
    "Name": ["Ali", "Hassan", "Mohammad"],
    "Age": [24, 18, 22],
    "City": ["Kabul", "Bamyan", "Herat"]
}
std_info = pd.DataFrame(data, columns=["Name", "City", "Age"])
std_info

       Name    City  Age
0       Ali   Kabul   24
1    Hassan  Bamyan   18
2  Mohammad   Herat   22

In [33]:
# 3. Adding Empty Column(s) to Existing Columns
data = {
    "Name": ["Ali", "Hassan", "Mohammad"],
    "Age": [24, 18, 22],
    "City": ["Kabul", "Bamyan", "Herat"]
}
std_info = pd.DataFrame(data, columns=["Name", "Last Name", "Age", "City"])
std_info

       Name Last Name  Age    City
0       Ali       NaN   24   Kabul
1    Hassan       NaN   18  Bamyan
2  Mohammad       NaN   22   Herat

In [34]:
# 4. Defining Columns During DataiFrame Creation
data =[
    ["Ali", 24, "Kabul"],
    ["Hassan", 18, "Bamyan"],
    ["Mohammad", 22, "Herat"]
]
std_info = pd.DataFrame(data, columns=["Name", "Age", "City"])
std_info

       Name  Age    City
0       Ali   24   Kabul
1    Hassan   18  Bamyan
2  Mohammad   22   Herat

In [35]:
# 5. Filtering Existing Data Structures
data = {
    "Name": ["Ali", "Hassan", "Mohammad"],
    "Age": [24, 18, 22],
    "City": ["Kabul", "Bamyan", "Herat"]
}
std_info = pd.DataFrame(data, columns=["Name", "Age"])
std_info

       Name  Age
0       Ali   24
1    Hassan   18
2  Mohammad   22

In [36]:
# 6. Creates an Empty DataFrame with Specific Columns
std_info = pd.DataFrame(columns=["STD_ID", "STD_Score", "STD_State"])
std_info

Empty DataFrame
Columns: [STD_ID, STD_Score, STD_State]
Index: []