***
---
# **Table of Contents**
> importing `pandas`

> ## __Series__
> * Introduction to `Series`
> * Creating `Series`

> ## __DataFrame__
> * Introduction to `DataFrme`
> * Creating `DataFrame`
---
***

### imporing pandas
To use `pandas`, import it using the statement `import pandas as pd`. The `as pd` is a universally accepted community convention that allows you to make the library's name shorter and easier to use. Pandas is typically imported at the very top of notebooks in the first executable cell.

In [52]:
import pandas as pd

## **Series**
---

### What a Series is
A Pandas Series is a one-dimensional labeled array capable of holding any data type, such as integers, floats, strings, or Python objects. Conceptually, it is like a single column in an Excel spreadsheet or a database table.

### Creating Series
To create a Pandas Series, use the `pd.Series()` constructor. Series can be build from various data sources like Python lists, NumPy arrays, dictionaries, or scalar values.

In [53]:
# Creating an empty Series
my_series = pd.Series()
my_series

Series([], dtype: object)

In [54]:
# Creating a Series from a Python list
my_series = pd.Series(["Apple", "Banana", "Oringe"])
my_series

0     Apple
1    Banana
2    Oringe
dtype: object

In [55]:
# Use the index parameter to specify explicit labels for your data.
list_data = ["Apple", "Banana", "Oringe"]
my_series = pd.Series(list_data, index=["A", "B", "C"])
my_series

A     Apple
B    Banana
C    Oringe
dtype: object

In [56]:
# Creating a Series from a Python dictionary
dict_data = {"Apple": 5, "Banana": 3, "Oringe": 7}
my_series = pd.Series(dict_data)
my_series

Apple     5
Banana    3
Oringe    7
dtype: int64

In [57]:
# Creating a Series frome a Numpy array
import numpy as np
np_data = np.array([1.4, 3.4, 8])
my_series = pd.Series(np_data)
my_series

0    1.4
1    3.4
2    8.0
dtype: float64

In [58]:
# Creating a Series from a scalar value
my_series = pd.Series(5, index=[x for x in "abcd"])
my_series

a    5
b    5
c    5
d    5
dtype: int64

In [59]:
# Creating a Series from a Python function
my_series = pd.Series(range(5))
my_series

0    0
1    1
2    2
3    3
4    4
dtype: int64

#### Image:
![Image of a Standard CSV File](../data/images/scv-file.png)

In [60]:
# Creating a Series from a CSV file
make_series = pd.read_csv("../data/scv-files/car-sales.csv", usecols=["Make"]).squeeze("columns") # Selects Make column from car-sales.csv
make_series

0    Toyota
1     Honda
2    Toyota
3       BMW
4    Nissan
5    Toyota
6     Honda
7     Honda
8    Toyota
9    Nissan
Name: Make, dtype: object

#### Image:
![Image of an Excel File](../data/images/excel-file.png)

In [61]:
# Creating a Series from a Excel file
price_series = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols=["Price"]).squeeze("columns") # Selects Price column of car-sales.xlsx
price_series

0     $4,000.00
1     $5,000.00
2     $7,000.00
3    $22,000.00
4     $3,500.00
5     $4,500.00
6     $7,500.00
7     $7,000.00
8     $6,250.00
9     $9,700.00
Name: Price, dtype: object

#### Image:
![Image of a Json File](../data/images/json-file.png)

In [62]:
# Creating a Series from a Jon File
json_data = pd.read_json("../data/json-files/house-price-parquet.json", lines=True)
stories_series = json_data["stories"] # Selects stories column of house-price-parquet.json
stories_series.head()

0    3
1    4
2    2
3    2
4    2
Name: stories, dtype: int64

## **DataFrame**
---

### What a DataFrame is
A Pandas DataFrame is a two-dimensional, tabular data structure in Python that organizes data into rows and columns, much like an Excel spreadsheet or a SQL database table. It can store different types of data such as numbers, text and dates across its columns.

### Creating DataFrame
To create a pandas DataFrame, use the `pd.DataFrame()` constructor. Pandas allows us to create a DataFrame from many data sources. We can create DataFrames directly from Python objects like lists and dictionaries or by reading data from external files like CSV, Excel or SQL databases.

In [63]:
# Creating an empty DataFrame
my_dataframe = pd.DataFrame()
print(my_dataframe)

Empty DataFrame
Columns: []
Index: []

In [64]:
# Creating a DataFrame from Python list
users_info = pd.DataFrame({"Name": ["Ali", "Mohammad", "Sadiq", "Hassan"], "Age": [22, 25, 18, 10]})
users_info

       Name  Age
0       Ali   22
1  Mohammad   25
2     Sadiq   18
3    Hassan   10

In [65]:
# Use the index parameter to specify explicit labels for your data.
names = ["Ali", "Mohammad", "Sadiq", "Hassan"]
ages = [22, 25, 18, 10]
users_info = pd.DataFrame({"Name": names,"Age": ages}, index=["A", "B", "C", "D"])
users_info

       Name  Age
A       Ali   22
B  Mohammad   25
C     Sadiq   18
D    Hassan   10

In [66]:
#  Creating a DataFrame from a list of lists (Row-Oriented)
data = [
    ['Ali', 22, 'Kabul'],
    ['Mohammad', 18, 'Bamyan'],
    ['Hussan', 25, 'Herat']
]
users_info = pd.DataFrame(data, columns=["Name", "Age", "City"])
users_info

       Name  Age    City
0       Ali   22   Kabul
1  Mohammad   18  Bamyan
2    Hussan   25   Herat

In [67]:
# Creating DataFrame from Python dictionary
data = {
    "Name":["Ali", "Mohammad", "Hassan"],
    "Age": [22, 18, 25],
    "City": ["Kabul", "Bamyan", "Herat"]
}
users_info = pd.DataFrame(data)
users_info

       Name  Age    City
0       Ali   22   Kabul
1  Mohammad   18  Bamyan
2    Hassan   25   Herat

In [68]:
# Creating a DataFrame from a list of dictionaries (Row-Oriented)
data = [
    {'Name': 'Ali', 'Age': 22, 'City': 'Kablu'},
    {'Name': 'Mohammad', 'Age': 18, 'City': 'Bamyan'},
    {'Name': 'Hassan', 'Age': 25, 'City': 'Herat'}
]

users_info = pd.DataFrame(data)
users_info

       Name  Age    City
0       Ali   22   Kablu
1  Mohammad   18  Bamyan
2    Hassan   25   Herat

In [69]:
# Creating a DataFrame from a Numpy array
data = {
    "A": np.array([1, 2, 3]),
    "B": np.array([4, 5, 6]),
    "C": np.array([7, 8, 9])
}
np_dataframe = pd.DataFrame(data)
np_dataframe

   A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

#### Image:
![Image of a Standard CSV File](../data/images/scv-file.png)

In [70]:
# Creating a DataFrame from a CSV file
car_sales = pd.read_csv("../data/scv-files/car-sales.csv")
car_sales.head()

     Make  Color  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

#### Image:
![Image of an Excel File](../data/images/excel-file.png)

In [71]:
# Creating a DataFrame from an excel file
car_sales_dataframe = pd.read_excel("../data/excel-files/car-sales.xlsx")
car_sales_dataframe

     Make  Color  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00
5  Toyota  Green          99213      4   $4,500.00
6   Honda   Blue          45698      4   $7,500.00
7   Honda   Blue          54738      4   $7,000.00
8  Toyota  White          60000      4   $6,250.00
9  Nissan  White          31600      4   $9,700.00

#### Image:
![Image of a Json File](../data/images/json-file.png)

In [72]:
# Creating a DataFrame from a Json file
house_price_parquet = pd.read_json("../data/json-files/house-price-parquet.json", lines=True)
house_price_parquet.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished