***
---
# __Table of Contents__

> ## __Importing Data__
> * From CSV Files

> ## __Common CSV Import Customizations__
> 1. `sep` Parameter
> 2. `header` Parameter
> 3. `names` Parameter
> 4. `index_col` Parameter
> 5. `skiprows` Parameter
> 6. `skipfooter` Parameter
> 7. `usecols` Parameter
> 8. `nrows` Parameter
> 9. `dtype` Parameter
> 10. `parse_dates` Parameter
> 11. `true_values` Parameter
> 12. `false_values` Parameter
> 13. `keep_default_na` Parameter
> 14. `na_values` Parameter
> 15. `na_filter` Parameter
> 16. `decimal` Parameter
> 17. `thousands` Parameter
> 18. `engine` Parameter
> 19. `comment` Parameter
---
***

In [1]:
import pandas as pd

## __Importing Data__
---

### Importing Data From CSV Files
To import data from a CSV file using Pandas, use the `pd.read_csv()` function. Without some customizations, `pd.read_csv()` method will convert the tabular file directly into a structured pandas DataFrame!

#### Image:
![Image of a CSV File](../data/images/csv-file.png)

In [2]:
# 1. A simple example of importing a csv file which is located locally in your computer
car_sales = pd.read_csv("../data/csv-files/car-sales.csv")
car_sales.head()

     Make  Color  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [3]:
# 2. A simple example of importing a csv file which is not located locally in your computer, but on the internet
# In this example we import a csv file from kaggle datasets.

## __Common CSV Import Customizations__
---

### 1. `sep` Parameter
the `sep` parameter stands for "separator" (or delimiter) and is used to specify the character or regular expression that splits the columns in your text file. 

By default, `sep=','` because standard Comma-Separated Values (CSV) files use a comma to separate data fields, but you can change it to `sep=';'`, `sep='\t'` or others depending on you datasets.

#### Image:
![Image of a Commas Separated CSV File](../data/images/csv-file.png)

In [4]:
# Default (,)
car_sales = pd.read_csv("../data/csv-files/car-sales.csv")
car_sales.head(3)

     Make  Color  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

#### Image:
![Image of a Semicolons Separated CSV File](../data/images/semicolons-separated-csv-file.png)

In [5]:
# Semicolons (;)
heart_disease = pd.read_csv("../data/csv-files/heart-disease.csv", skiprows=2, sep=";")
heart_disease.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1

#### Image:
![Image of a Tabs Separated CSV File](../data/images/tabs-separated-csv-file.png)

In [6]:
# Tabs
car_sales = pd.read_csv("../data/csv-files/car-sales-missing-data.csv", skiprows=[0, 3, 7], sep="\t")
car_sales

     Make  Color  Odometer (KM)  Doors     Price
0  Toyota  White       150043.0    4.0   $4,000
1   Honda    NaN        87899.0    4.0   $5,000
2  Toyota   Blue            NaN    NaN   $7,000
3     BMW  Black        11179.0    5.0  $22,000
4  Nissan  White       213095.0    4.0       NaN
5  Toyota    NaN        99213.0    4.0   $4,500
6   Honda   Blue        45698.0    NaN   $7,500
7   Honda   Blue            NaN    4.0   $7,000
8  Toyota  White        60000.0    4.0       NaN
9  Nissan  White        31600.0    4.0   $9,700

### 2. `header` Parameter
The `header` parameter determines which row (or rows) of your CSV file will be used as the DataFrame's column names. 

The default is `header='infer'`, but you can pass `None`, a integer number or a list of integers.

#### Image:
![Image of a CSV File with Header](../data/images/csv-file.png)

In [7]:
# 2.1 Default Behavior (header='infer' <=> header=0)
car_sales = pd.read_csv("../data/csv-files/car-sales.csv")
car_sales.head(3)

     Make  Color  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

In [8]:
# 2.1.1 Default Behavior (header='infer' <=> header=0)
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", skiprows=1)
car_sales.head(3)

   Toyota  White  150043  4   $4,000.00
0   Honda    Red   87899  4   $5,000.00
1  Toyota   Blue   32549  3   $7,000.00
2     BMW  Black   11179  5  $22,000.00

In [9]:
# 2.1.2 Default Behavior (header='infer' <=> header=None because names are given)
created_names = ["A", "B", "C", "D", "E"]
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", names=created_names)
car_sales.head(3)

        A      B              C      D          E
0    Make  Color  Odometer (KM)  Doors      Price
1  Toyota  White         150043      4  $4,000.00
2   Honda    Red          87899      4  $5,000.00

In [10]:
# If your file has headers but you want to replace them with your own names, pass header=0 alongside your custom names list.
# This overrides the original text rather than pushing it down into the first data row.

car_sales = pd.read_csv("../data/csv-files/car-sales.csv", header=0, names=created_names)
car_sales.head(3)

        A      B       C  D          E
0  Toyota  White  150043  4  $4,000.00
1   Honda    Red   87899  4  $5,000.00
2  Toyota   Blue   32549  3  $7,000.00

In [11]:
# 2.2 CSV File Has No Headers (header=None)
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", skiprows=1, header=None,)
car_sales.head(3)

        0      1       2  3          4
0  Toyota  White  150043  4  $4,000.00
1   Honda    Red   87899  4  $5,000.00
2  Toyota   Blue   32549  3  $7,000.00

#### Image:
![Image of Multi Level Columns CSV File](../data/images/multi-level-columns-csv.png)

In [12]:
# 2.3 Handling MultiIndex Headers (header=[int, int, ...])
# Use when your CSV file contains multi-level (hierarchical) column headers.
multi_level_columns = pd.read_csv("../data/csv-files/multi-level-columns.csv", header=[0, 1])
multi_level_columns

      Location       Metrics
          City State Revenue Profit
0     New York    NY     100     40
1  Los Angeles    CA     120     50
2      Chicago    IL      90     30

### 3. `names` Parameter
Is used to explicitly define custom column names for your resulting DataFrame.

#### Image:
![Image of CSV File with No Header Row](../data/images/read-csv-names.png)

In [13]:
# 3.1 The CSV has NO Header Row
created_names = ["Name", "Color", "driven (KM)", "Tires", "Cost"]
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", skiprows=1, names=created_names)
car_sales.head(3)

     Name  Color  driven (KM)  Tires       Cost
0  Toyota  White       150043      4  $4,000.00
1   Honda    Red        87899      4  $5,000.00
2  Toyota   Blue        32549      3  $7,000.00

#### Image
![Image of a CSV File with Header Row](../data/images/csv-file.png)

In [14]:
# 3.2 Replaced or Overriding an Existing Header Row
created_names = ["Name", "Color", "driven (KM)", "Tires", "Cost"]
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", header=0, names=created_names)
car_sales.head(3)

     Name  Color  driven (KM)  Tires       Cost
0  Toyota  White       150043      4  $4,000.00
1   Honda    Red        87899      4  $5,000.00
2  Toyota   Blue        32549      3  $7,000.00

### 4. `index_col` Parameter
`index_col` parameter specifies which column(s) to use as the row labels (index) of the resulting DataFrame. 

By default `index_col=None`,  which prompts `pandas` to generate an automatic integer index (0, 1, 2, ...). Other things that you can pass are, `False`, `0`, a string(name) or a `list`.

#### Image:
![Image of a CSV File](../data/images/read-csv-usecols.png)

In [15]:
# 4.1 Default Behavior (index_col=None)
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", comment="#",
                               sep=";")
erp_sales_report.head(3)

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,NaN
2,823,2026-01-06,NaN,NaN,NaN,NaN,NaN

In [16]:
# 4.2 Using a Single Column Name or Position
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", comment="#",
                               sep=";", index_col="Date") # You can also pass index here
erp_sales_report.head(3)

,Transaction_ID,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
Date,,,,,,
2026-01-05,821,John Doe,Electronics,2.0,650.00,0.10
2026-01-05,822,Jane Smith,Clothing,5.0,25.50,NaN
2026-01-06,823,NaN,NaN,NaN,NaN,NaN

#### Image:
![Image of a CSV File](../data/images/read-csv-skipfooter.png)

In [17]:
# 4.3 Creating a MultiIndex (Hierarchical Index)
laptop_sales = pd.read_csv("../data/csv-files/laptop-sales.csv", skipfooter=3, engine="python",
                           index_col=["Year", "Month", "Day"]) # You can also pass indexes here
print(type(laptop_sales.index))
laptop_sales

<class 'pandas.core.indexes.multi.MultiIndex'>

                Hour   Product  Revenue
Year Month Day
2026 6     10      9    Laptop     1200
           10     14     Mouse       25
           11     11  Keyboard       75
           12     16   Monitor      300

#### Image:
![Image of a CSV File](../data/images/read-csv-index-col.png)

In [18]:
# 4.4 Disabling Automatic Inference (index_col=False)
messy_inventory = pd.read_csv("../data/csv-files/messy-inventory.csv", index_col=False)
messy_inventory

   Item_ID            Item_Name Warehouse  Stock_Level  Unnamed: 4
0  INV-001       Wireless Mouse     North          150       22.50
1  INV-002  Mechanical Keyboard      East           85       79.99
2  INV-003            USB-C Hub      West          200       45.00
3  INV-004       Gaming Monitor     North           40      299.99
4  INV-005      Ergonomic Chair     South           12      189.50

In [19]:
# If you don't set index_col to False, it will be like this
# It is because the dataset has 4 column names, but 5 columns at all
# Python will automatically assume the first axtra column as index column
messy_inventory = pd.read_csv("../data/csv-files/messy-inventory.csv")
messy_inventory

                     Item_ID Item_Name  Warehouse  Stock_Level  Unnamed: 4
INV-001       Wireless Mouse     North        150        22.50         NaN
INV-002  Mechanical Keyboard      East         85        79.99         NaN
INV-003            USB-C Hub      West        200        45.00         NaN
INV-004       Gaming Monitor     North         40       299.99         NaN
INV-005      Ergonomic Chair     South         12       189.50         NaN

##### Note!
Pandas only forces `index_col=None` to behave differently from `index_col=False` when the header line has exactly \(N\) names, but the data lines have exactly \(N+1\) values.

### 5. `skiprows` Parameter
Allows you to exclude specific lines or blocks of data from being parsed when loading a CSV file. 

By default `skiprows=None`, but you can pass an integer, a list of integers or a callable/lambda fuction.

#### Image:
![Image of a CSV File](../data/images/read-csv-skiprows1.png)

In [20]:
# 5.1 An Integer (Skip N Rows from Start)
heart_disease = pd.read_csv("../data/csv-files/heart-disease.csv", sep=";", skiprows=2)
heart_disease.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1

#### Image:
![Skip Specific Positions Image](../data/images/read-csv-skiprows2.png)

In [21]:
# 5.2 A List of Integers (Skip Specific Row Indices)
car_sales_missing = pd.read_csv("../data/csv-files/car-sales-missing-data.csv", sep="\t", skiprows=[0, 3, 7])
car_sales_missing

     Make  Color  Odometer (KM)  Doors     Price
0  Toyota  White       150043.0    4.0   $4,000
1   Honda    NaN        87899.0    4.0   $5,000
2  Toyota   Blue            NaN    NaN   $7,000
3     BMW  Black        11179.0    5.0  $22,000
4  Nissan  White       213095.0    4.0       NaN
5  Toyota    NaN        99213.0    4.0   $4,500
6   Honda   Blue        45698.0    NaN   $7,500
7   Honda   Blue            NaN    4.0   $7,000
8  Toyota  White        60000.0    4.0       NaN
9  Nissan  White        31600.0    4.0   $9,700

In [22]:
# 5.3 A Callable / Lambda Function (Conditional Skipping)
# 5.3.1 Checking Against an Outside List
skipped_records = [0, 3, 7]
car_sales_missing = pd.read_csv("../data/csv-files/car-sales-missing-data.csv", sep="\t", 
                                skiprows=lambda x: x in skipped_records)
car_sales_missing

     Make  Color  Odometer (KM)  Doors     Price
0  Toyota  White       150043.0    4.0   $4,000
1   Honda    NaN        87899.0    4.0   $5,000
2  Toyota   Blue            NaN    NaN   $7,000
3     BMW  Black        11179.0    5.0  $22,000
4  Nissan  White       213095.0    4.0       NaN
5  Toyota    NaN        99213.0    4.0   $4,500
6   Honda   Blue        45698.0    NaN   $7,500
7   Honda   Blue            NaN    4.0   $7,000
8  Toyota  White        60000.0    4.0       NaN
9  Nissan  White        31600.0    4.0   $9,700

In [23]:
# 5.3.2 Checking a Pattern (Using Math)
car_sales_extended = pd.read_csv("../data/csv-files/car-sales-extended.csv", skiprows=lambda x: x%5==0)
car_sales_extended.head(3)

    Honda  White   35431  4  15323
0     BMW   Blue  192714  5  19943
1   Honda  White   84714  4  28343
2  Toyota  White  154365  4  13434

In [24]:
# 5.3.3 Random Sampling (Using Probability)
import random
car_sales_extended = pd.read_csv("../data/csv-files/car-sales-extended.csv", 
                                 skiprows=lambda x: x>0 and random.random()>0.8)
car_sales_extended.head(3)

     Make  Color  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2  Nissan   Blue         181577      3  14043

### 6. `skipfooter` Parameter"
It allows you to exclude a specific number of lines from the bottom of a CSV file before loading it into a DataFrame. It is useful for ignoring summary totals, signatures, or metadata footers appended to raw data files.

You must explicitly set this engine parameter to `"python"`!

#### Image:
![Image of CSV a File](../data/images/read-csv-skipfooter.png)

In [25]:
laptop_sales = pd.read_csv("../data/csv-files/laptop-sales.csv", skipfooter=3, engine="python")
laptop_sales

   Year  Month  Day  Hour   Product  Revenue
0  2026      6   10     9    Laptop     1200
1  2026      6   10    14     Mouse       25
2  2026      6   11    11  Keyboard       75
3  2026      6   12    16   Monitor      300

### 7. `usecols` Parameter
`usecols` parameter allows you to select and load only specific columns from a CSV file into memory. This is highly useful for reducing memory usage and speeding up file parsing when dealing with massive datasets. 

You can pass a list of column names, a list of integer indices, or a custom lambda function to the parameter.

#### Image:
![Image of a CSV File](../data/images/csv-file.png)

In [26]:
##### 7.1 Column Names (String List)
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", usecols=["Make", "Price"])
car_sales.head(3)

     Make      Price
0  Toyota  $4,000.00
1   Honda  $5,000.00
2  Toyota  $7,000.00

In [27]:
# 7.2 Position Index (Integer List)
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", usecols=[0, 4])
car_sales.head(3)

     Make      Price
0  Toyota  $4,000.00
1   Honda  $5,000.00
2  Toyota  $7,000.00

In [28]:
# 7.3 Dynamic Filtering (Callable/Lambda)
# 7.3.1 Black-listing
ignored_cols = ["Make", "Odometer (KM)"]
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", usecols=lambda col: col not in ignored_cols)
car_sales.head(3)

   Color  Doors      Price
0  White      4  $4,000.00
1    Red      4  $5,000.00
2   Blue      3  $7,000.00

#### Image:
![Image of a CSV File](../data/images/read-csv-usecols.png)

In [29]:
# 7.3.2 Pattern Matching (Partial Names)
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", skiprows=3,
                               sep=";", usecols=lambda col: any(x in col.lower() for x in ["id", "name", "price"]))
erp_sales_report.head(3)

   Transaction_ID Customer_Name Unit_Price
0             821      John Doe     650.00
1             822    Jane Smith      25.50
2             823           NaN     120.00

### 8. `nrows` Parameter
It specifies the exact number of data rows to read from a CSV file into a DataFrame. 

By default `nrows=None`, but you can pass any integer.

#### Image:
![Image of a CSV File](../data/images/csv-file.png)

In [30]:
# 8.1 Getting Only Headers (Zero Rows)
car_sales_extended = pd.read_csv("../data/csv-files/car-sales-extended.csv", nrows=0)
print("Length: ", len(car_sales_extended))
car_sales_extended.head(3)

Length:  0

Empty DataFrame
Columns: [Make, Color, Odometer (KM), Doors, Price]
Index: []

In [31]:
# 8.2 Previewing a Large File to Inspect Columns
car_sales_extended = pd.read_csv("../data/csv-files/car-sales-extended.csv", nrows=200)
print("Length: ", len(car_sales_extended))
car_sales_extended.head(3)

Length:  200

    Make  Color  Odometer (KM)  Doors  Price
0  Honda  White          35431      4  15323
1    BMW   Blue         192714      5  19943
2  Honda  White          84714      4  28343

In [32]:
# 8.3 Interaction with skiprows
car_sales_extended = pd.read_csv("../data/csv-files/car-sales-extended.csv", 
                                 skiprows=lambda index: index>0 and index%2==0, nrows=350)
print("Length: ", len(car_sales_extended))
car_sales_extended.head(3)

Length:  350

     Make  Color  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1   Honda  White          84714      4  28343
2  Nissan   Blue         181577      3  14043

### 9. `dtype` Parameter
The `dtype` parameter allows you to explicitly force specific data types for your columns while importing a CSV file. 

By default, pandas tries to guess (infer) data types automatically, but this can lead to high memory consumption or incorrect data type assignments (like leading zeros being dropped from postal codes or ID numbers).

#### Image:
![Image of a CSV File](../data/images/csv-file.png)

In [33]:
# The original data types of this CSV file
car_sales = pd.read_csv("../data/csv-files/car-sales.csv")
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Color          10 non-null     object
 2   Odometer (KM)  10 non-null     int64
 3   Doors          10 non-null     int64
 4   Price          10 non-null     object
dtypes: int64(2), object(3)
memory usage: 532.0+ bytes

In [34]:
# 9.1 Set a single data type for ALL columns
car_sales = pd.read_csv("../data/csv-files/car-sales.csv", dtype=str)
car_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Make           10 non-null     object
 1   Color          10 non-null     object
 2   Odometer (KM)  10 non-null     object
 3   Doors          10 non-null     object
 4   Price          10 non-null     object
dtypes: object(5)
memory usage: 532.0+ bytes

#### Image:
![Image of a CSV File](../data/images/read-csv-usecols.png)

In [35]:
# 9.2 Set Specific Types per Column (Most Common)
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                               skiprows=3, na_values=["missing", "unknown", "N/A", "?", "#N/A", "#QNAN", "-999"], 
                              dtype={
                                  "Transaction_ID": str,
                                  "Date": str,
                                  "Quantity": "float32",
                                  "Unit_Price": "float32",
                                  # "Discount_Applied": "float32"
                              })
erp_sales_report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    24 non-null     object
 1   Date              24 non-null     object
 2   Customer_Name     20 non-null     object
 3   Product_Category  18 non-null     object
 4   Quantity          20 non-null     float32
 5   Unit_Price        21 non-null     float32
 6   Discount_Applied  13 non-null     float64
dtypes: float32(2), float64(1), object(4)
memory usage: 1.3+ KB

In [36]:
erp_sales_report.head(3)

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,00821,2026-01-05,John Doe,Electronics,2.0,650.0,0.1
1,00822,2026-01-05,Jane Smith,Clothing,5.0,25.5,NaN
2,00823,2026-01-06,NaN,Home,NaN,120.0,0.0

In [37]:
# 9.3 Set Types using Column Positions
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, na_values=["missing", "unknown", "N/A", "?", "#N/A", "#QNAN", "-999"],
                              dtype={
                                  0: str,
                                  1: str, 
                                  4:"float32", 
                                  5:"float32", 
                                  # 6:"float32"
                              })
erp_sales_report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    24 non-null     object
 1   Date              24 non-null     object
 2   Customer_Name     20 non-null     object
 3   Product_Category  18 non-null     object
 4   Quantity          20 non-null     float32
 5   Unit_Price        21 non-null     float32
 6   Discount_Applied  13 non-null     float64
dtypes: float32(2), float64(1), object(4)
memory usage: 1.3+ KB

### 10. `parse_dates` Parameter
It used to automatically convert text-based columns into proper `datetime64` object data types while loading data. 

By default, pandas imports dates as `strings (object type)`, which eliminates the need to manually convert columns using `pd.to_datetime()` after loading your file.

#### Image:
![Image of a CSV File](../data/images/read-csv-usecols.png)

In [38]:
# 10.1 Pass a list of column name or names
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, parse_dates=["Date"])
erp_sales_report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    24 non-null     int64
 1   Date              24 non-null     datetime64[ns]
 2   Customer_Name     22 non-null     object
 3   Product_Category  19 non-null     object
 4   Quantity          20 non-null     float64
 5   Unit_Price        23 non-null     object
 6   Discount_Applied  19 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 1.4+ KB

In [39]:
# 10.2 Pass a list of column index or indexes
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, parse_dates=[1])
erp_sales_report.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction_ID    24 non-null     int64
 1   Date              24 non-null     datetime64[ns]
 2   Customer_Name     22 non-null     object
 3   Product_Category  19 non-null     object
 4   Quantity          20 non-null     float64
 5   Unit_Price        23 non-null     object
 6   Discount_Applied  19 non-null     object
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 1.4+ KB

In [40]:
# 10.3 Parse the Index Automatically
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, index_col="Date", parse_dates=True)
print("Index Type: ", type(erp_sales_report.index))
erp_sales_report.head(3)

Index Type:  <class 'pandas.core.indexes.datetimes.DatetimeIndex'>

,Transaction_ID,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
Date,,,,,,
2026-01-05,821,John Doe,Electronics,2.0,650.00,0.10
2026-01-05,822,Jane Smith,Clothing,5.0,25.50,NaN
2026-01-06,823,NaN,Home,NaN,120.00,0.00

### 11. `true_values` Parameter
It is used to specify a list of additional strings that should be treated as the boolean `True`. 

By default, pandas only recognizes case-insensitive variations of 'True' (such as "true", "True", "TRUE") as boolean `True`. If your dataset uses alternative terms like "Yes", "Y", or "Active", you use this parameter alongside `false_values` to parse them cleanly into actual booleans during data import.


### 12. `false_values` Parameter
It is used to specify a list of additional strings that should be parsed as the boolean `False`.

By default, pandas only recognizes case-insensitive variations of 'False' (such as "false", "FALSE", "False") as boolean `False`. If your dataset uses alternative representations like "No", "N", "No", or "0", you use this parameter alongside `true_values` to parse them cleanly into actual booleans during data import.

#### Image:
![Image of a CSV File](../data/images/read-csv-true-values-false-values.png)

In [41]:
# Define your custom True representations
students_payment_report = pd.read_csv("../data/csv-files/students-payment-report.csv",
                                     true_values=["Active", "Yes", "TRUE"],
                                     false_values=["Inactive", "No", "FALSE"]
                                     )
students_payment_report.dtypes

user_id                int64
name                  object
is_active               bool
marketing_opt_in        bool
has_paid_invoice        bool
paid_for_new_books     int64
dtype: object

### 13. `keep_default_na` Parameter
`keep_default_na` parameter in controls whether built-in null identifiers (like "`NA`", "`NaN`", "`null`", or blank cells) are automatically converted into `NaN` values. It defaults to `True`.

#### Default Missing Values in Pandas
If you do not change `keep_default_na`, the following built-in strings are automatically parsed as `NaN`:
* `""` (empty strings), `NaN`, `nan`, `null`, `NULL`
* `N/A`, `n/a`, `NA`, `#N/A`, `#NA`
* `-NaN`, `-nan`, `1.#IND`, `-1.#IND`, `1.#QNAN`, `-1.#QNAN`

#### Image:
![Quick Breakdown of keep_default_na Behavior](../data/images/quick-breakdown-of-keep-default-na-behavior.png)

#### Image:
![Image of a CSF File](../data/images/read-csv-na-values.png)

In [42]:
# 13.1 Default (keep_default_na=True)
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv",
                              sep=";", skiprows=3)
erp_sales_report

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,NaN
2,823,2026-01-06,NaN,Home,NaN,120.00,0.00
3,824,2026-01-06,Alice Brown,NaN,1.0,missing,0.05
4,825,2026-01-07,Charlie Green,NaN,3.0,45.00,unknown
5,826,2026-01-07,David White,Clothing,1.0,15.99,0.00
6,827,2026-01-08,Eva Black,Electronics,4.0,899.99,-999
7,828,2026-01-08,Frank Miller,NaN,2.0,55.00,NaN
8,829,2026-01-09,-999,Sports,NaN,35.50,0.00
9,830,2026-01-09,Henry Wilson,Electronics,1.0,1200.00,0.20
10,831,2026-01-10,Ivy Taylor,NaN,10.0,12.00,missing
11,832,2026-01-10,Jack Moore,Home,1.0,85.00,0.00
12,833,2026-01-11,Kevin Thomas,-999,2.0,65.00,NaN
13,834,2026-01-11,NaN,Electronics,5.0,150.00,NaN
14,835,2026-01-12,Mary Martin,Clothing,3.0,40.00,0.00
15,836,2026-01-12,Nathan Clark,NaN,NaN,250.00,?
16,837,2026-01-13,Olivia Rodriguez,Sports,1.0,95.00,unknown
17,838,2026-01-13,Paul Lewis,Electronics,2.0,450.00,0.10
18,839,2026-01-14,?,Clothing,4.0,?,0.00
19,840,2026-01-14,Rachel Hall,Home,1.0,175.00,0.15
20,841,2026-01-15,Sam Allen,Sports,6.0,18.00,NaN
21,842,2026-01-15,Tina Young,Electronics,NaN,NaN,0.00
22,843,2026-01-16,Victor King,Clothing,2.0,60.00,missing
23,844,2026-01-16,Wendy Wright,Home,1.0,300.00,0.10

In [43]:
# 13.2 keep_default_na=False
# Check the difference between keep_default_na=True and keep_default_na=False by looking at the outpot 13.1 & 13.2
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv",
                              sep=";", skiprows=3, keep_default_na=False)
erp_sales_report

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5,25.50,N/A
2,823,2026-01-06,#N/A,Home,,120.00,0.00
3,824,2026-01-06,Alice Brown,NA,1,missing,0.05
4,825,2026-01-07,Charlie Green,1.#QNAN,3,45.00,unknown
5,826,2026-01-07,David White,Clothing,1,15.99,0.00
6,827,2026-01-08,Eva Black,Electronics,4,899.99,-999
7,828,2026-01-08,Frank Miller,1.#QNAN,2,55.00,N/A
8,829,2026-01-09,-999,Sports,,35.50,0.00
9,830,2026-01-09,Henry Wilson,Electronics,1,1200.00,0.20
10,831,2026-01-10,Ivy Taylor,NA,10,12.00,missing
11,832,2026-01-10,Jack Moore,Home,1,85.00,0.00
12,833,2026-01-11,Kevin Thomas,-999,2,65.00,#N/A
13,834,2026-01-11,1.#QNAN,Electronics,5,150.00,N/A
14,835,2026-01-12,Mary Martin,Clothing,3,40.00,0.00
15,836,2026-01-12,Nathan Clark,NA,,250.00,?
16,837,2026-01-13,Olivia Rodriguez,Sports,1,95.00,unknown
17,838,2026-01-13,Paul Lewis,Electronics,2,450.00,0.10
18,839,2026-01-14,?,Clothing,4,?,0.00
19,840,2026-01-14,Rachel Hall,Home,1,175.00,0.15
20,841,2026-01-15,Sam Allen,Sports,6,18.00,N/A
21,842,2026-01-15,Tina Young,Electronics,,#N/A,0.00
22,843,2026-01-16,Victor King,Clothing,2,60.00,missing
23,844,2026-01-16,Wendy Wright,Home,1,300.00,0.10

#### Note!
A common issue occurs when a column contains valid data (such as North America coded as "NA"), but pandas converts it to `NaN`. To stop this, set `keep_default_na=False` so pandas only flags what you explicitly tell it to flag.

In [44]:
# 13.3 set keep_default_na=False and pass explicitly na_values
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, keep_default_na=False,
                               na_values=["unknown", "missing", "#QNAN", "1.#QNAN", "N/A", "#N/A", "NaN"])
erp_sales_report

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5,25.50,NaN
2,823,2026-01-06,NaN,Home,,120.00,0.00
3,824,2026-01-06,Alice Brown,NA,1,NaN,0.05
4,825,2026-01-07,Charlie Green,NaN,3,45.00,NaN
5,826,2026-01-07,David White,Clothing,1,15.99,0.00
6,827,2026-01-08,Eva Black,Electronics,4,899.99,-999
7,828,2026-01-08,Frank Miller,NaN,2,55.00,NaN
8,829,2026-01-09,-999,Sports,,35.50,0.00
9,830,2026-01-09,Henry Wilson,Electronics,1,1200.00,0.20
10,831,2026-01-10,Ivy Taylor,NA,10,12.00,NaN
11,832,2026-01-10,Jack Moore,Home,1,85.00,0.00
12,833,2026-01-11,Kevin Thomas,-999,2,65.00,NaN
13,834,2026-01-11,NaN,Electronics,5,150.00,NaN
14,835,2026-01-12,Mary Martin,Clothing,3,40.00,0.00
15,836,2026-01-12,Nathan Clark,NA,,250.00,?
16,837,2026-01-13,Olivia Rodriguez,Sports,1,95.00,NaN
17,838,2026-01-13,Paul Lewis,Electronics,2,450.00,0.10
18,839,2026-01-14,?,Clothing,4,?,0.00
19,840,2026-01-14,Rachel Hall,Home,1,175.00,0.15
20,841,2026-01-15,Sam Allen,Sports,6,18.00,NaN
21,842,2026-01-15,Tina Young,Electronics,,NaN,0.00
22,843,2026-01-16,Victor King,Clothing,2,60.00,NaN
23,844,2026-01-16,Wendy Wright,Home,1,300.00,0.10

### 14. `na_values` Parameter
The `na_values` parameter is used to specify custom strings, numbers, or markers that should be recognized as missing data (`NaN`). 

By default, pandas automatically interprets empty cells and common strings like `#N/A`, `N/A`, `NULL`, `NaN`, and null as missing values. If your dataset uses unique placeholders (like `?`, `-999`, or `Missing`), you must declare them using na_values.

#### Image:
![Quick Breakdown of keep_default_na Behavior](../data/images/quick-breakdown-of-keep-default-na-behavior.png)

#### Image:
![Image of a CSF File](../data/images/read-csv-na-values.png)

In [45]:
# 14.1 Default
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3)
erp_sales_report

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,NaN
2,823,2026-01-06,NaN,Home,NaN,120.00,0.00
3,824,2026-01-06,Alice Brown,NaN,1.0,missing,0.05
4,825,2026-01-07,Charlie Green,NaN,3.0,45.00,unknown
5,826,2026-01-07,David White,Clothing,1.0,15.99,0.00
6,827,2026-01-08,Eva Black,Electronics,4.0,899.99,-999
7,828,2026-01-08,Frank Miller,NaN,2.0,55.00,NaN
8,829,2026-01-09,-999,Sports,NaN,35.50,0.00
9,830,2026-01-09,Henry Wilson,Electronics,1.0,1200.00,0.20
10,831,2026-01-10,Ivy Taylor,NaN,10.0,12.00,missing
11,832,2026-01-10,Jack Moore,Home,1.0,85.00,0.00
12,833,2026-01-11,Kevin Thomas,-999,2.0,65.00,NaN
13,834,2026-01-11,NaN,Electronics,5.0,150.00,NaN
14,835,2026-01-12,Mary Martin,Clothing,3.0,40.00,0.00
15,836,2026-01-12,Nathan Clark,NaN,NaN,250.00,?
16,837,2026-01-13,Olivia Rodriguez,Sports,1.0,95.00,unknown
17,838,2026-01-13,Paul Lewis,Electronics,2.0,450.00,0.10
18,839,2026-01-14,?,Clothing,4.0,?,0.00
19,840,2026-01-14,Rachel Hall,Home,1.0,175.00,0.15
20,841,2026-01-15,Sam Allen,Sports,6.0,18.00,NaN
21,842,2026-01-15,Tina Young,Electronics,NaN,NaN,0.00
22,843,2026-01-16,Victor King,Clothing,2.0,60.00,missing
23,844,2026-01-16,Wendy Wright,Home,1.0,300.00,0.10

In [46]:
# 14.2 Pass a List
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, na_values=["unknown", "missing", "?", "-999"])
erp_sales_report

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,NaN
2,823,2026-01-06,NaN,Home,NaN,120.00,0.00
3,824,2026-01-06,Alice Brown,NaN,1.0,NaN,0.05
4,825,2026-01-07,Charlie Green,NaN,3.0,45.00,NaN
5,826,2026-01-07,David White,Clothing,1.0,15.99,0.00
6,827,2026-01-08,Eva Black,Electronics,4.0,899.99,NaN
7,828,2026-01-08,Frank Miller,NaN,2.0,55.00,NaN
8,829,2026-01-09,NaN,Sports,NaN,35.50,0.00
9,830,2026-01-09,Henry Wilson,Electronics,1.0,1200.00,0.20
10,831,2026-01-10,Ivy Taylor,NaN,10.0,12.00,NaN
11,832,2026-01-10,Jack Moore,Home,1.0,85.00,0.00
12,833,2026-01-11,Kevin Thomas,NaN,2.0,65.00,NaN
13,834,2026-01-11,NaN,Electronics,5.0,150.00,NaN
14,835,2026-01-12,Mary Martin,Clothing,3.0,40.00,0.00
15,836,2026-01-12,Nathan Clark,NaN,NaN,250.00,NaN
16,837,2026-01-13,Olivia Rodriguez,Sports,1.0,95.00,NaN
17,838,2026-01-13,Paul Lewis,Electronics,2.0,450.00,0.10
18,839,2026-01-14,NaN,Clothing,4.0,NaN,0.00
19,840,2026-01-14,Rachel Hall,Home,1.0,175.00,0.15
20,841,2026-01-15,Sam Allen,Sports,6.0,18.00,NaN
21,842,2026-01-15,Tina Young,Electronics,NaN,NaN,0.00
22,843,2026-01-16,Victor King,Clothing,2.0,60.00,NaN
23,844,2026-01-16,Wendy Wright,Home,1.0,300.00,0.10

#### Note!
A common issue occurs when a column contains valid data (such as North America coded as "NA"), but pandas converts it to `NaN`. To stop this, set `keep_default_na=False` so pandas only flags what you explicitly tell it to flag.

In [47]:
# 14.3 set keep_default_na=False and pass explicitly na_values
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, keep_default_na=False,
                               na_values=["unknown", "missing", "?", "-999", "#QNAN", "1.#QNAN", "N/A", "#N/A", "NaN"])
erp_sales_report

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5,25.50,NaN
2,823,2026-01-06,NaN,Home,,120.00,0.00
3,824,2026-01-06,Alice Brown,NA,1,NaN,0.05
4,825,2026-01-07,Charlie Green,NaN,3,45.00,NaN
5,826,2026-01-07,David White,Clothing,1,15.99,0.00
6,827,2026-01-08,Eva Black,Electronics,4,899.99,NaN
7,828,2026-01-08,Frank Miller,NaN,2,55.00,NaN
8,829,2026-01-09,NaN,Sports,,35.50,0.00
9,830,2026-01-09,Henry Wilson,Electronics,1,1200.00,0.20
10,831,2026-01-10,Ivy Taylor,NA,10,12.00,NaN
11,832,2026-01-10,Jack Moore,Home,1,85.00,0.00
12,833,2026-01-11,Kevin Thomas,NaN,2,65.00,NaN
13,834,2026-01-11,NaN,Electronics,5,150.00,NaN
14,835,2026-01-12,Mary Martin,Clothing,3,40.00,0.00
15,836,2026-01-12,Nathan Clark,NA,,250.00,NaN
16,837,2026-01-13,Olivia Rodriguez,Sports,1,95.00,NaN
17,838,2026-01-13,Paul Lewis,Electronics,2,450.00,0.10
18,839,2026-01-14,NaN,Clothing,4,NaN,0.00
19,840,2026-01-14,Rachel Hall,Home,1,175.00,0.15
20,841,2026-01-15,Sam Allen,Sports,6,18.00,NaN
21,842,2026-01-15,Tina Young,Electronics,,NaN,0.00
22,843,2026-01-16,Victor King,Clothing,2,60.00,NaN
23,844,2026-01-16,Wendy Wright,Home,1,300.00,0.10

### 15. `na_filter` Parameter
`na_filter` parameter is a boolean flag (`True` by default) that controls whether pandas detects and filters missing value markers (like empty cells, NaN, NULL, N/A) into actual `NaN` values.

The core difference between `na_filter` and `keep_default_na` is their scope: `na_filter` is a master switch that turns missing value detection completely on or off, while `keep_default_na` controls which specific strings pandas considers to be missing values.

#### Image:m
![Image of a CSv File](../data/images/read-csv-na-values.png)

In [48]:
# If na_filter=True, keep_default_na and na_values work!
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, na_values=["unknown", "missing", "?", "-999"], na_filter=True)
erp_sales_report

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,NaN
2,823,2026-01-06,NaN,Home,NaN,120.00,0.00
3,824,2026-01-06,Alice Brown,NaN,1.0,NaN,0.05
4,825,2026-01-07,Charlie Green,NaN,3.0,45.00,NaN
5,826,2026-01-07,David White,Clothing,1.0,15.99,0.00
6,827,2026-01-08,Eva Black,Electronics,4.0,899.99,NaN
7,828,2026-01-08,Frank Miller,NaN,2.0,55.00,NaN
8,829,2026-01-09,NaN,Sports,NaN,35.50,0.00
9,830,2026-01-09,Henry Wilson,Electronics,1.0,1200.00,0.20
10,831,2026-01-10,Ivy Taylor,NaN,10.0,12.00,NaN
11,832,2026-01-10,Jack Moore,Home,1.0,85.00,0.00
12,833,2026-01-11,Kevin Thomas,NaN,2.0,65.00,NaN
13,834,2026-01-11,NaN,Electronics,5.0,150.00,NaN
14,835,2026-01-12,Mary Martin,Clothing,3.0,40.00,0.00
15,836,2026-01-12,Nathan Clark,NaN,NaN,250.00,NaN
16,837,2026-01-13,Olivia Rodriguez,Sports,1.0,95.00,NaN
17,838,2026-01-13,Paul Lewis,Electronics,2.0,450.00,0.10
18,839,2026-01-14,NaN,Clothing,4.0,NaN,0.00
19,840,2026-01-14,Rachel Hall,Home,1.0,175.00,0.15
20,841,2026-01-15,Sam Allen,Sports,6.0,18.00,NaN
21,842,2026-01-15,Tina Young,Electronics,NaN,NaN,0.00
22,843,2026-01-16,Victor King,Clothing,2.0,60.00,NaN
23,844,2026-01-16,Wendy Wright,Home,1.0,300.00,0.10

In [49]:
# But if na_filter=False, keep_default_na and na_values don't work!
erp_sales_report = pd.read_csv("../data/csv-files/ERP_sales_report_east_20260607_084932.csv", sep=";",
                              skiprows=3, na_values=["unknown", "missing", "?", "-999"], na_filter=False)
erp_sales_report

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5,25.50,N/A
2,823,2026-01-06,#N/A,Home,,120.00,0.00
3,824,2026-01-06,Alice Brown,NA,1,missing,0.05
4,825,2026-01-07,Charlie Green,1.#QNAN,3,45.00,unknown
5,826,2026-01-07,David White,Clothing,1,15.99,0.00
6,827,2026-01-08,Eva Black,Electronics,4,899.99,-999
7,828,2026-01-08,Frank Miller,1.#QNAN,2,55.00,N/A
8,829,2026-01-09,-999,Sports,,35.50,0.00
9,830,2026-01-09,Henry Wilson,Electronics,1,1200.00,0.20
10,831,2026-01-10,Ivy Taylor,NA,10,12.00,missing
11,832,2026-01-10,Jack Moore,Home,1,85.00,0.00
12,833,2026-01-11,Kevin Thomas,-999,2,65.00,#N/A
13,834,2026-01-11,1.#QNAN,Electronics,5,150.00,N/A
14,835,2026-01-12,Mary Martin,Clothing,3,40.00,0.00
15,836,2026-01-12,Nathan Clark,NA,,250.00,?
16,837,2026-01-13,Olivia Rodriguez,Sports,1,95.00,unknown
17,838,2026-01-13,Paul Lewis,Electronics,2,450.00,0.10
18,839,2026-01-14,?,Clothing,4,?,0.00
19,840,2026-01-14,Rachel Hall,Home,1,175.00,0.15
20,841,2026-01-15,Sam Allen,Sports,6,18.00,N/A
21,842,2026-01-15,Tina Young,Electronics,,#N/A,0.00
22,843,2026-01-16,Victor King,Clothing,2,60.00,missing
23,844,2026-01-16,Wendy Wright,Home,1,300.00,0.10

### 16. `decimal` Parameter
It specifies which character the parser should recognize as the decimal separator when reading numeric columns. This parameter is highly useful for parsing European datasets or localized files where a comma (`,`) represents the decimal point.

By default, pandas looks for a period (`.`), but you can change this to a comma (`,`) or any other character to correctly parse international data formats.

#### Image:
![Image of a CSV File](../data/images/read-csv-decimal-thousands.png)

In [50]:
# You can see the result in Tax_Rate column
spm_sales = pd.read_csv("../data/csv-files/supermarket-sales.csv", sep=";", decimal=",")
spm_sales

  Product_ID     Category Units_Sold Revenue_EUR  Tax_Rate
0       P101  Electronics      1.200   14.500,75      0.21
1       P102    Groceries     25.450    3.180,50      0.06
2       P103     Clothing        450    9.890,00      0.21
3       P104         Home      3.000   22.400,25      0.15

In [51]:
spm_sales.dtypes

Product_ID      object
Category        object
Units_Sold      object
Revenue_EUR     object
Tax_Rate       float64
dtype: object

In [52]:
# You can see the result in all numeric columns
spm_sales = pd.read_csv("../data/csv-files/supermarket-sales.csv", sep=";", thousands=".", decimal=",")
spm_sales

  Product_ID     Category  Units_Sold  Revenue_EUR  Tax_Rate
0       P101  Electronics        1200     14500.75      0.21
1       P102    Groceries       25450      3180.50      0.06
2       P103     Clothing         450      9890.00      0.21
3       P104         Home        3000     22400.25      0.15

In [53]:
spm_sales.dtypes

Product_ID      object
Category        object
Units_Sold       int64
Revenue_EUR    float64
Tax_Rate       float64
dtype: object

### 17. `thousands` Parameter
`thousands` parameter specifies which character is used as the thousands separator in numeric columns. 

By default, pandas does not assume a thousands separator. If your file contains numbers formatted with commas or periods to separate thousands (e.g., 1,000,000), pandas will read them as text strings (object dtype). Setting this parameter strips those characters so pandas can parse them into integers or floats.

#### Image:
![Image of a CSV File](../data/images/read-csv-decimal-thousands.png)

In [54]:
# You can see the result in Units_Sold column
spm_sales = pd.read_csv("../data/csv-files/supermarket-sales.csv", sep=";", thousands=".")
spm_sales

  Product_ID     Category  Units_Sold Revenue_EUR Tax_Rate
0       P101  Electronics        1200   14.500,75     0,21
1       P102    Groceries       25450    3.180,50     0,06
2       P103     Clothing         450    9.890,00     0,21
3       P104         Home        3000   22.400,25     0,15

In [55]:
spm_sales.dtypes

Product_ID     object
Category       object
Units_Sold      int64
Revenue_EUR    object
Tax_Rate       object
dtype: object

In [56]:
# You can see the result in all numeric columns
spm_sales = pd.read_csv("../data/csv-files/supermarket-sales.csv", sep=";", decimal=",", thousands=".")
spm_sales

  Product_ID     Category  Units_Sold  Revenue_EUR  Tax_Rate
0       P101  Electronics        1200     14500.75      0.21
1       P102    Groceries       25450      3180.50      0.06
2       P103     Clothing         450      9890.00      0.21
3       P104         Home        3000     22400.25      0.15

In [57]:
spm_sales.dtypes

Product_ID      object
Category        object
Units_Sold       int64
Revenue_EUR    float64
Tax_Rate       float64
dtype: object

### 18. `engine` Parameter
The `engine` parameter specifies the underlying parsing engine used to read and process your text files. Selecting the right engine allows you to balance execution speed, memory efficiency, and specific feature requirements.

#### 1. `engine='c'` (The Default)
* __Speed:__ Extremely fast because it runs on compiled `C` code.
* __Use Case:__ Best for standard, clean, or massive CSV datasets.
* __Limitations:__ It does not support regex delimiters, skipfooter, or advanced fallback behaviors.

#### 2. `engine='python'`
* __Speed:__ Significantly slower because it processes data in pure `Python`.
* __Use Case:__ Use this when you have complex or unconventional formatting.
* __Key Features:__ Supports multi-character regex delimiters (e.g., `sep='[;,]'`), skipping footers (`skipfooter=N`), and auto-detecting delimiters using Python’s built-in sniffer.

#### 3. `engine='pyarrow'`
* __Speed:__ The fastest engine option for large-scale data.
* __Use Case:__ Highly recommended for massive files where maximum I/O performance is critical.
* __Key Features:__ It uses Apache Arrow and is the only engine that natively supports multithreading to parallelize file reading.
* __Limitations:__ It requires the pyarrow library to be installed and may not support every minor formatting edge case.

### 19. `comment` Parameter
he comment parameter takes ___a single character___. Pandas ignores everything after this character on a line. If a line starts with it, the whole line is skipped. If it appears mid-line, pandas chops off the rest of that line. It parses only the data before the character.

#### Image:
![Image of a CSV File](../data/images/read-csv-skiprows1.png)

In [58]:
# Commenting rows
heart_disease = pd.read_csv("../data/csv-files/heart-disease.csv", sep=";", comment="#")
heart_disease.head(3)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1