***
---
# __Table of Contents__

> ## __Importing Data__
> * From Excel Files

> ## __Common Excel Import Customizations__
> 1. `sheet_name` Parameter
> 2. `header` Parameter
> 3. `names` Parameter
> 4. `index_col` Parameter
> 5. `skiprows` Parameter
> 6. `skipfooter` Parameter
> 7. `usecols` Parameter
> 8. `nrows` Parameter
> 9. `dtype` Parameter
> 10. `parse_dates` Parameter
> 11. `true_values` Parameter
> 12. `false_values` Parameter
> 13. `keep_default_na` Parameter
> 14. `na_values` Parameter
> 15. `na_filter` Parameter
> 16. `decimal` Parameter
> 17. `thousands` Parameter
> 18. `engine` Parameter
> 19. `comment` Parameter
---
***

In [1]:
import pandas as pd

## __Importing Data__
---

### Importing Data From Excel Files
To import data from an Excel file into `Python`, use the `pd.read_excel()` function from the `Pandas` library. This function converts your spreadsheet into a structured `DataFrame` object.

#### Image:
![Image of an Excel File](../data/images/excel-file.png)

In [2]:
# A simple example of importing a excel file (First Sheet) which is located locally in your computer
excel_df = pd.read_excel("../data/excel-files/car-sales.xlsx")
excel_df.head(3)

     Make  Color  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

In [3]:
# 2. A simple example of importing a csv file which is not located locally in your computer, but on the internet

## __Common Excel Import Customizations__
---

### 1. `sheet_name` Parameter
It determines which specific worksheet or worksheets to load from your Excel file. 

By default, it is set to `0`, which imports only the first sheet as a `DataFrame`.

#### Image:
![Image of a Excel File with Two Sheets](../data/images/read-excel-sheet-name.png)

In [4]:
# 1.1 Load a Specific Sheet
# set sheet_name to a number like 0 or to sheet's name like sheet1
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", sheet_name="car-sales-extended") 
car_sales.head(3)

    Make  Color  Odometer (KM)  Doors  Price
0  Honda  White          35431      4  15323
1    BMW   Blue         192714      5  19943
2  Honda  White          84714      4  28343

In [5]:
# 1.2 Load Multiple Specific Sheets
# set sheet_name to numbers like [0, 1] or sheet's names like ["sheet1", "sheet2"]
# Passing a list returns a dictionary where the keys are the sheet identifiers and the values are individual DataFrames:
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", sheet_name=[0, 1])
car_sales_sheet1 = car_sales[0]
car_sales_extended = car_sales[1]
car_sales_sheet1.head(3)

     Make  Color  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

In [6]:
car_sales_extended.head(3)

    Make  Color  Odometer (KM)  Doors  Price
0  Honda  White          35431      4  15323
1    BMW   Blue         192714      5  19943
2  Honda  White          84714      4  28343

### 2. `header` Prameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `2. header Parameter` section, if you need a refresher.

### 3. `names` Parameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `3. names Parameter` section, if you need a refresher.

### 4. `index_col` Parameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `4. index_col Parameter` section, if you need a refresher.

### 5. `skiprows` Parameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `5. skiprows Parameter` section, if you need a refresher.

### 6. `skipfooter` Parameter
It is used to ignore a specific number of rows at the very bottom (footer) of an Excel worksheet during import.

The primary difference with `read_csv` is that `skipfooter` works automatically in `read_excel`, but requires you to manually switch the parsing `engine` in `read_csv`.

#### Image:
![Image of an Excel File](../data/images/read-excel-skipfooter.png)

In [7]:
laptop_sales = pd.read_excel("../data/excel-files/laptop-sales.xlsx", skiprows=[3], skipfooter=3)
laptop_sales

   Year  Month  Day  Hour   Product  Revenue
0  2026      6   10     9    Laptop     1200
1  2026      6   10    14     Mouse       25
2  2026      6   11    11  Keyboard       75
3  2026      6   12    16   Monitor      300

### 7. `usecols` Parameter
It allows you to select and load only specific columns into memory from a spreadsheet. Using this parameter improves speed and drastically reduces memory consumption when working with massive Excel workbooks.

#### Image:
![Image of an Excel File](../data/images/excel-file.png)

In [8]:
# 7.1 Excel Column Letters (String)
# Both upper case letters and lower case letters work(a or A, b or B)
# 7.1.1 Specific column(s)
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols="A")
car_sales.head(3)

     Make
0  Toyota
1   Honda
2  Toyota

In [9]:
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols="a, B, E") 
car_sales.head(3)

     Make  Color      Price
0  Toyota  White  $4,000.00
1   Honda    Red  $5,000.00
2  Toyota   Blue  $7,000.00

In [10]:
# 7.1 Excel Column Letters (String)
# 7.1.2 Range of columns
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols="B:E")
car_sales.head(3)

   Color  Odometer (KM)  Doors      Price
0  White         150043      4  $4,000.00
1    Red          87899      4  $5,000.00
2   Blue          32549      3  $7,000.00

In [11]:
# 7.1 Excel Column Letters (String)
# 7.1.3 Mixed columns and ranges
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols="A:C, E")
car_sales.head(3)

     Make  Color  Odometer (KM)      Price
0  Toyota  White         150043  $4,000.00
1   Honda    Red          87899  $5,000.00
2  Toyota   Blue          32549  $7,000.00

In [12]:
# 7.2 Column Names (List of Strings)
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols=["Make"])
car_sales.head(3)

     Make
0  Toyota
1   Honda
2  Toyota

In [13]:
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols=["Make", "Price"])
car_sales.head(3)

     Make      Price
0  Toyota  $4,000.00
1   Honda  $5,000.00
2  Toyota  $7,000.00

In [14]:
# 7.3 Column Integer Indices (List of Integers)
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols=[4])
car_sales.head(3)

       Price
0  $4,000.00
1  $5,000.00
2  $7,000.00

In [15]:
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols=[0, 4])
car_sales.head(3)

     Make      Price
0  Toyota  $4,000.00
1   Honda  $5,000.00
2  Toyota  $7,000.00

In [16]:
# 7.4 Conditional Filtering (Callable/Function)
needed_cols = ["Make", "Color", "Odometer (KM)", "Price"]
car_sales = pd.read_excel("../data/excel-files/car-sales.xlsx", usecols=lambda x: x in needed_cols)
car_sales.head(3)

     Make  Color  Odometer (KM)      Price
0  Toyota  White         150043  $4,000.00
1   Honda    Red          87899  $5,000.00
2  Toyota   Blue          32549  $7,000.00

### 8. `nrows` Parameter
The syntax for this parameter is identical to how it is used in `read_csv`. However, while they are syntactically the same, they behave differently behind the scenes because Excel files contain pre-formatted cell metadata, whereas CSVs are just raw plain text. 

To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `12. parse_dates Parameter` section, if you needed.

### 9. `dtype` Parameter
The syntax for this parameter is identical to how it is used in `read_csv`. However, while they are syntactically the same, they behave differently behind the scenes because Excel files contain pre-formatted cell metadata, whereas CSVs are just raw plain text. 

To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `9. dtype Parameter` section, if you needed.

### 10. `parse_dates` Parameter
The syntax for this parameter is identical to how it is used in `read_csv`. However, while they are syntactically the same, they behave differently behind the scenes because Excel files contain pre-formatted cell metadata, whereas CSVs are just raw plain text. 

To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `10. parse_dates Parameter` section, if you needed.

### 11. `true_values` Parameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `11. true_values Parameter` section, if you need a refresher.

### 12. `false_values` Parameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `12. false_values Parameter` section, if you need a refresher.

### 13. `keep_default_na` Parameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `13. keep_default_na Parameter` section, if you need a refresher.

### 14. `na_values` Parameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `14. na_values Parameter` section, if you need a refresher.

### 15. `na_filter` Parameter
This parameter works exactly the same way as it does in `read_csv`. To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `15. na_filter Parameter` section, if you need a refresher.

### 16. `decimal` Parameter
The syntax for this parameter is identical to how it is used in `read_csv`. However, while they are syntactically the same, they behave differently behind the scenes because Excel files contain pre-formatted cell metadata, whereas CSVs are just raw plain text. 

To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `16. decimal Parameter` section, if you needed.

### 17. `thousnads` Parameter
The syntax for this parameter is identical to how it is used in `read_csv`. However, while they are syntactically the same, they behave differently behind the scenes because Excel files contain pre-formatted cell metadata, whereas CSVs are just raw plain text. 

To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `17. thousands Parameter` section, if you needed.

### 18. `engine` Parameter
It specifies the underlying Python library used to parse the Excel file. Because pandas does not natively read Excel binaries, it relies on third-party backend "engines" to convert spreadsheets into DataFrames.

By default (`engine=None`), pandas automatically selects the best engine based on your file extension. However, explicitly defining the engine is highly recommended to optimize speed, bypass file corruption errors, or handle specialized formats.


#### 1. `engine='openpyxl'`
* __Extension:__ .xlsx, .xlsm
* __Speed:__ Moderate.
* __Use Case:__ The standard default engine for modern, XML-based Excel files.
* __Limitation:__ High memory consumption on massive files.

#### 2. `engine='calamine'`
* __Extension:__ All formats (.xlsx, .xlsb, .xls, .ods)
* __Speed:__ Extremely fast (Rust-backed).
* __Use Case:__ The best choice for massive datasets needing maximum performance.
* __Limitation:__ Requires installing the python-calamine package.

#### 3. `engine='xlrd'`
* __Extension:__ .xlsSpeed: Fast.
* __Use Case:__ Strictly reserved for legacy, pre-2007 Excel files.
* __Limitation:__ No longer supports modern .xlsx files due to security updates.

#### 4. `engine='pyxlsb'`
* __Extension:__ .xlsb
* __Speed:__ Fast.
* __Use Case:__ Dedicated exclusively to Excel Binary Workbooks.
* __Limitation:__ Cannot read standard XML or legacy sheets.

#### 5. `engine='odf'`
* __Extension:__ .ods
* __Speed:__ Slow.
* __Use Case:__ Specifically for open-source OpenDocument sheets (LibreOffice/OpenOffice).
* __Limitation:__ Very narrow use case; poor performance on large files.

### 19. `comment` Parameter
It parameter is used to find a specific character in text cells and ignore any text that follows it on that line.

#### How It Works
* __Default Value:__ `comment=None` (it does not parse or drop any text based on a comment character).
* __Input:__ It accepts a single character string (like '#' or '//').
* __Behavior:__ If the specified character is found inside a cell, pandas ignores all data from that character to the end of that row line. If a line starts with the comment character, the whole line is skipped.

#### `comment` in `read_csv` vs `read_excel`
* __`comment` in `read_csv`:__ Completely strips the row. The row index skips it entirely, and the DataFrame is shorter.
* __`comment` in `read_excel`:__ It cuts off the text inside a cell. If it is in the middle of a cell, all text after it is erased. If it starts the row, the whole row becomes blank. However, it does not delete the row, so the row index and total count stay the same.

#### Image:
![Image of an Excel File](../data/images/read-excel-skipfooter.png)

In [17]:
laptop_sales = pd.read_excel("../data/excel-files/laptop-sales.xlsx", comment="#")
laptop_sales

     Year  Month   Day  Hour   Product  Revenue
0  2026.0    6.0  10.0   9.0    Laptop   1200.0
1  2026.0    6.0  10.0  14.0     Mouse     25.0
2  2026.0    6.0   NaN   NaN      None      NaN
3  2026.0    6.0  11.0  11.0  Keyboard     75.0
4  2026.0    6.0  12.0  16.0   Monitor    300.0
5     NaN    NaN   NaN   NaN      None      NaN
6     NaN    NaN   NaN   NaN      None      NaN
7     NaN    NaN   NaN   NaN      None      NaN