***
---
# __Table of Contents__

> ## __Importing Data__
> * From Json Files

> ## __Common Json Import Customizations__
> 1. `lines` Parameter
> 2. `orient` Parameter
> 3. `dtype` Parameter
> 4. `convert_dates` Parameter
---
***

In [1]:
import pandas as pd

## __Importing Data__
---

### Importing Data From Json Files
To import data from JSON files using `pandas.read_json()`, pass the file path directly into the function to convert the JSON data into a structured `DataFrame`.

#### Image:
![Image of a Json File](../data/images/simple-json-file.png)

In [2]:
# Basic Local File Import
house_price = pd.read_json("../data/json-files/car-sales.json")
house_price.head()

     Make  Color  Odometer (KM)  Doors       Price
0  Toyota  White         150043      4   $4,000.00
1   Honda    Red          87899      4   $5,000.00
2  Toyota   Blue          32549      3   $7,000.00
3     BMW  Black          11179      5  $22,000.00
4  Nissan  White         213095      4   $3,500.00

In [3]:
# Fetching Directly From a URL / API

## __Common Json Import Customizations__
---

### 1. `lines` Parameter
The `lines` parameter controls whether the input file should be read as a line-delimited JSON format. By default, `lines=False`. When you set `lines=True`, pandas treats each individual line in the file as a distinct, valid JSON object rather than parsing the entire file as a single massive JSON array or dictionary.

#### Image:
![Image of a Json File](../data/images/simple-json-file.png)

In [4]:
# 1. Standard JSON Array (lines=False)
car_sales = pd.read_json("../data/json-files/car-sales.json")
car_sales.head(3)

     Make  Color  Odometer (KM)  Doors      Price
0  Toyota  White         150043      4  $4,000.00
1   Honda    Red          87899      4  $5,000.00
2  Toyota   Blue          32549      3  $7,000.00

#### Image:
![Image of a Json File](../data/images/json-file.png)

In [5]:
# 2. JSON Lines / NDJSON (lines=True)
house_price = pd.read_json("../data/json-files/house-price-parquet.json", lines=True)
house_price.head(3)

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished

### 2. `orient` Parameter
The `orient` parameter specifies the expected layout or structure of the incoming JSON string or file so that pandas can correctly map it into a `DataFrame` or `Series`. By default, if `typ='frame'`, pandas assumes `orient='columns'`.

#### 1. `orient='records'` (Most Common)
Expects a list of dictionaries, where each dictionary represents a row with column-value pairs.
* __Best for:__ Standard web APIs and general data transfer.
* __JSON Structure:__
  ```
                  [
                    {"Name": "Alice", "Age": 25},
                    {"Name": "Bob", "Age": 30}
                  ]
  ```

#### 2. `orient='columns'` (Default)
Expects a nested dictionary structured as {#column -> {#index -> value}}.
* __Best for:__ Preserving row indexes without repeating column names for every row.
* __JSON Structure:__
  ```
                  {
                    "Name": {"0": "Alice", "1": "Bob"},
                    "Age": {"0": 25, "1": 30}
                  }
  ```

#### 3. `orient='index'`
Expects a nested dictionary structured as {#index -> {#column -> value}}.
* __Best for:__ Key-value lookups where the primary keys are the row labels.
* __JSON Structure:__
  ```
                  {
                    "0": {"Name": "Alice", "Age": 25},
                    "1": {"Name": "Bob", "Age": 30}
                  }
  ```

#### 4. `orient='split'`
Expects a dictionary with explicit, separate keys for columns, index, and data arrays.
* __Best for:__ Maximizing space efficiency while maintaining explicit axis names.
* __JSON Structure:__
  ```
                  {
                    "columns": ["Name", "Age"],
                    "index": [0, 1],
                    "data": [
                         ["Alice", 25],
                         ["Bob", 30]
                      ]
                  }
  ```

#### 5. `orient='values'`
Expects a bare array of arrays containing only the raw data values. No index or column labels are preserved.
* __Best for:__ Highly compressed data transfers where schemas are documented elsewhere.
* __JSON Structure:__
  ```
                  [
                    ["Alice", 25],
                    ["Bob", 30]
                  ]

  ```

#### 6. `orient='table'`
Expects a dictionary containing a schema field describing the data types and a data field formatted like records.
* __Best for:__ Safely transferring data between pandas sessions while keeping exact data types intact.
* __JSON Structure:__
  ```
                  {
                    "schema": {
                      "fields": [
                        {"name": "index", "type": "integer"},
                        {"name": "Name", "type": "string"},
                        {"name": "Age", "type": "integer"}
                      ],
                      "primaryKey": ["index"],
                      "pandas_version": "1.4.0"
                    },
                    "data": [
                      {"index": 0, "Name": "Alice", "Age": 25},
                      {"index": 1, "Name": "Bob", "Age": 30}
                    ]
                  }
  ```

### 3. `dtype` Parameter
The syntax for this parameter is identical to how it is used in `read_csv`. However, while they are syntactically the same, they behave differently behind the scenes because Excel files contain pre-formatted cell metadata, whereas CSVs are just raw plain text. 

To keep things efficient and avoid wasting time repeating notes, I skipped writing it here. You can check the `importing_csv_data` notebook `9. dtype Parameter` section, if you needed.

### 4. `convert_dates` Parameter
The `convert_dates` parameter controls whether date-like strings or Unix timestamps in your JSON data are automatically parsed into Pandas `datetime64[ns]` objects.

In [6]:
# 1. Default Behavior (True)
erp_sales_report = pd.read_json("../data/json-files/ERP_sales_report_east_20260607_084932.json")
erp_sales_report.head(3)

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,None
2,823,2026-01-06,None,Home,NaN,120.00,0.00

In [7]:
erp_sales_report.dtypes

Transaction_ID               int64
Date                datetime64[ns]
Customer_Name               object
Product_Category            object
Quantity                   float64
Unit_Price                  object
Discount_Applied            object
dtype: object

In [8]:
# 2. Disabling Date Conversion (False)
erp_sales_report = pd.read_json("../data/json-files/ERP_sales_report_east_20260607_084932.json",
                                convert_dates=False)
erp_sales_report.head(3)

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,None
2,823,2026-01-06,None,Home,NaN,120.00,0.00

In [9]:
erp_sales_report.dtypes

Transaction_ID        int64
Date                 object
Customer_Name        object
Product_Category     object
Quantity            float64
Unit_Price           object
Discount_Applied     object
dtype: object

In [10]:
# If we set keep_default_dates=False, read_json fuction stops to search for date columns by its own.
erp_sales = pd.read_json("../data/json-files/ERP_sales_report_east_20260607_084932.json", 
                         keep_default_dates=False)
erp_sales.head(3)

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,None
2,823,2026-01-06,None,Home,NaN,120.00,0.00

In [11]:
erp_sales.dtypes

Transaction_ID        int64
Date                 object
Customer_Name        object
Product_Category     object
Quantity            float64
Unit_Price           object
Discount_Applied     object
dtype: object

In [12]:
# 3. Specifying Target Column(s)
erp_sales = pd.read_json("../data/json-files/ERP_sales_report_east_20260607_084932.json", 
                         keep_default_dates=False, convert_dates=["Date"])
erp_sales.head(3)

,Transaction_ID,Date,Customer_Name,Product_Category,Quantity,Unit_Price,Discount_Applied
0,821,2026-01-05,John Doe,Electronics,2.0,650.00,0.10
1,822,2026-01-05,Jane Smith,Clothing,5.0,25.50,None
2,823,2026-01-06,None,Home,NaN,120.00,0.00

In [13]:
erp_sales.dtypes

Transaction_ID               int64
Date                datetime64[ns]
Customer_Name               object
Product_Category            object
Quantity                   float64
Unit_Price                  object
Discount_Applied            object
dtype: object